Add option to silence output from update script

diff --git a/update b/update
--- a/update
+++ b/update
@@ -2,22 +2,35 @@
 
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 OS=$(uname)
+QUIET=0
 
-echo -n "Updating config..."
-pushd $DIR 1>&/dev/null
-git pull 1>&/dev/null
-if [ $? -eq 0 ]; then
-  if [ "$OS" == "Darwin" ]; then
-    echo $' [ \e[0;32mOK\e[0m ]'
+usage() { echo "Usage: $0 [-q]" 1>&2; exit 1; }
+
+while getopts ":q" o; do
+  case "${o}" in
+    q) QUIET=1;;
+    *) usage;;
+  esac
+done
+shift $((OPTIND-1))
+
+if [ $QUIET -eq 0 ]; then echo -n "Updating config..."; fi
+pushd $DIR 1> /dev/null
+git pull 1> /dev/null
+if [ $QUIET -eq 0 ]; then
+  if [ $? -eq 0 ]; then
+    if [ "$OS" == "Darwin" ]; then
+      echo $' [ \e[0;32mOK\e[0m ]'
+    else
+      echo -e " [ \e[0;32mOK\e[0m ]"
+    fi
   else
-    echo -e " [ \e[0;32mOK\e[0m ]"
-  fi
-else
-  if [ "$OS" == "Darwin" ]; then
-    echo $' [ \e[0;31mFAILED\e[0m ]'
-  else
-    echo -e " [ \e[0;31mFAILED\e[0m ]"
+    if [ "$OS" == "Darwin" ]; then
+      echo $' [ \e[0;31mFAILED\e[0m ]'
+    else
+      echo -e " [ \e[0;31mFAILED\e[0m ]"
+    fi
   fi
 fi
-popd 1>&/dev/null
+popd 1> /dev/null
 
